// Copyright 2022 Sudo Technology Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: sudo/service/online_service_common.proto

package service

import (
	context "context"
	protobuf "github.com/sudo-privacy/sudo-sdk-go/v2/protobuf/basic/protobuf"
	enums "github.com/sudo-privacy/sudo-sdk-go/v2/protobuf/basic/protobuf/service/enums"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncStatus int32

const (
	SyncStatus_UNKNOWN   SyncStatus = 0
	SyncStatus_DEPLOYING SyncStatus = 1
	SyncStatus_SUCCESS   SyncStatus = 2
	SyncStatus_FAILED    SyncStatus = 3
	SyncStatus_UPDATING  SyncStatus = 4
)

// Enum value maps for SyncStatus.
var (
	SyncStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "DEPLOYING",
		2: "SUCCESS",
		3: "FAILED",
		4: "UPDATING",
	}
	SyncStatus_value = map[string]int32{
		"UNKNOWN":   0,
		"DEPLOYING": 1,
		"SUCCESS":   2,
		"FAILED":    3,
		"UPDATING":  4,
	}
)

func (x SyncStatus) Enum() *SyncStatus {
	p := new(SyncStatus)
	*p = x
	return p
}

func (x SyncStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sudo_service_online_service_common_proto_enumTypes[0].Descriptor()
}

func (SyncStatus) Type() protoreflect.EnumType {
	return &file_sudo_service_online_service_common_proto_enumTypes[0]
}

func (x SyncStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncStatus.Descriptor instead.
func (SyncStatus) EnumDescriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{0}
}

type CheckTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId uint64 `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Token     string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	PartyId   string `protobuf:"bytes,3,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
}

func (x *CheckTokenRequest) Reset() {
	*x = CheckTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenRequest) ProtoMessage() {}

func (x *CheckTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenRequest.ProtoReflect.Descriptor instead.
func (*CheckTokenRequest) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{0}
}

func (x *CheckTokenRequest) GetServiceId() uint64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *CheckTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CheckTokenRequest) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

type CheckTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *CheckTokenResponse) Reset() {
	*x = CheckTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenResponse) ProtoMessage() {}

func (x *CheckTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenResponse.ProtoReflect.Descriptor instead.
func (*CheckTokenResponse) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{1}
}

func (x *CheckTokenResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type BucketDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId uint64 `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// 桶序号
	BucketId []uint64 `protobuf:"varint,2,rep,packed,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	// 列名
	ColumnNames []string `protobuf:"bytes,3,rep,name=column_names,json=columnNames,proto3" json:"column_names,omitempty"`
}

func (x *BucketDataRequest) Reset() {
	*x = BucketDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketDataRequest) ProtoMessage() {}

func (x *BucketDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketDataRequest.ProtoReflect.Descriptor instead.
func (*BucketDataRequest) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{2}
}

func (x *BucketDataRequest) GetServiceId() uint64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *BucketDataRequest) GetBucketId() []uint64 {
	if x != nil {
		return x.BucketId
	}
	return nil
}

func (x *BucketDataRequest) GetColumnNames() []string {
	if x != nil {
		return x.ColumnNames
	}
	return nil
}

type SyncClientDeployInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId uint64              `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Token     string              `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	PartyInfo *protobuf.PartyInfo `protobuf:"bytes,3,opt,name=party_info,json=partyInfo,proto3" json:"party_info,omitempty"`
}

func (x *SyncClientDeployInfoRequest) Reset() {
	*x = SyncClientDeployInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncClientDeployInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncClientDeployInfoRequest) ProtoMessage() {}

func (x *SyncClientDeployInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncClientDeployInfoRequest.ProtoReflect.Descriptor instead.
func (*SyncClientDeployInfoRequest) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{3}
}

func (x *SyncClientDeployInfoRequest) GetServiceId() uint64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *SyncClientDeployInfoRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SyncClientDeployInfoRequest) GetPartyInfo() *protobuf.PartyInfo {
	if x != nil {
		return x.PartyInfo
	}
	return nil
}

type ClientInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketCount uint64              `protobuf:"varint,1,opt,name=bucket_count,json=bucketCount,proto3" json:"bucket_count,omitempty"`
	PartyInfo   *protobuf.PartyInfo `protobuf:"bytes,2,opt,name=party_info,json=partyInfo,proto3" json:"party_info,omitempty"`
	// OT 矩阵序列化为字节
	OtxClient []byte `protobuf:"bytes,3,opt,name=otx_client,json=otxClient,proto3" json:"otx_client,omitempty"`
	Token     string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{4}
}

func (x *ClientInfo) GetBucketCount() uint64 {
	if x != nil {
		return x.BucketCount
	}
	return 0
}

func (x *ClientInfo) GetPartyInfo() *protobuf.PartyInfo {
	if x != nil {
		return x.PartyInfo
	}
	return nil
}

func (x *ClientInfo) GetOtxClient() []byte {
	if x != nil {
		return x.OtxClient
	}
	return nil
}

func (x *ClientInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SyncClientDeployInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status SyncStatus `protobuf:"varint,1,opt,name=status,proto3,enum=sudo.protobuf.service.SyncStatus" json:"status,omitempty"`
	// deploy进度，返回百分比
	Progress float32 `protobuf:"fixed32,2,opt,name=progress,proto3" json:"progress,omitempty"`
	// 不可区分度
	IndiscernibilityDegree uint64 `protobuf:"varint,3,opt,name=indiscernibility_degree,json=indiscernibilityDegree,proto3" json:"indiscernibility_degree,omitempty"`
	// 匹配列
	KeyColumns []string `protobuf:"bytes,4,rep,name=key_columns,json=keyColumns,proto3" json:"key_columns,omitempty"`
	// deploy失败时才有值
	ErrMsg string `protobuf:"bytes,5,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	// 可查列
	LabelColumns []string `protobuf:"bytes,6,rep,name=label_columns,json=labelColumns,proto3" json:"label_columns,omitempty"`
	// client info 需要再启动 deployment client 传入
	ClientInfoId string         `protobuf:"bytes,7,opt,name=client_info_id,json=clientInfoId,proto3" json:"client_info_id,omitempty"`
	ClientInfo   *ClientInfo    `protobuf:"bytes,8,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	Type         enums.SVCType  `protobuf:"varint,9,opt,name=type,proto3,enum=sudo.protobuf.service.enums.SVCType" json:"type,omitempty"`                           // deploy mode, see deploy_mode definition for more details
	DataMode     enums.DataMode `protobuf:"varint,10,opt,name=data_mode,json=dataMode,proto3,enum=sudo.protobuf.service.enums.DataMode" json:"data_mode,omitempty"` // data mode, see data_mode definition for more details
	// 存放业务属性
	Context map[string]string `protobuf:"bytes,11,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SyncClientDeployInfoResponse) Reset() {
	*x = SyncClientDeployInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncClientDeployInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncClientDeployInfoResponse) ProtoMessage() {}

func (x *SyncClientDeployInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncClientDeployInfoResponse.ProtoReflect.Descriptor instead.
func (*SyncClientDeployInfoResponse) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{5}
}

func (x *SyncClientDeployInfoResponse) GetStatus() SyncStatus {
	if x != nil {
		return x.Status
	}
	return SyncStatus_UNKNOWN
}

func (x *SyncClientDeployInfoResponse) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *SyncClientDeployInfoResponse) GetIndiscernibilityDegree() uint64 {
	if x != nil {
		return x.IndiscernibilityDegree
	}
	return 0
}

func (x *SyncClientDeployInfoResponse) GetKeyColumns() []string {
	if x != nil {
		return x.KeyColumns
	}
	return nil
}

func (x *SyncClientDeployInfoResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *SyncClientDeployInfoResponse) GetLabelColumns() []string {
	if x != nil {
		return x.LabelColumns
	}
	return nil
}

func (x *SyncClientDeployInfoResponse) GetClientInfoId() string {
	if x != nil {
		return x.ClientInfoId
	}
	return ""
}

func (x *SyncClientDeployInfoResponse) GetClientInfo() *ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

func (x *SyncClientDeployInfoResponse) GetType() enums.SVCType {
	if x != nil {
		return x.Type
	}
	return enums.SVCType_UNKNOWN_TYPE
}

func (x *SyncClientDeployInfoResponse) GetDataMode() enums.DataMode {
	if x != nil {
		return x.DataMode
	}
	return enums.DataMode_UNKNOWN_DATA_MODE
}

func (x *SyncClientDeployInfoResponse) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// ["a1", "zhao", "167"]
type Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item []string `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
}

func (x *Row) Reset() {
	*x = Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{6}
}

func (x *Row) GetItem() []string {
	if x != nil {
		return x.Item
	}
	return nil
}

// ["a1", "zhao", "167"],
// ["a2", "qian", "155"],
type BucketData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*Row `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *BucketData) Reset() {
	*x = BucketData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketData) ProtoMessage() {}

func (x *BucketData) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketData.ProtoReflect.Descriptor instead.
func (*BucketData) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{7}
}

func (x *BucketData) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

// {
//    ["a1", "zhao", "167"],
//    ["a2", "qian", "155"],
//    ["a3", "zhang", "153"],
// }, // bucket #1
// {
//    ["b1", "sun", "155"],
//    ["b2", "li", "115"],
// }, // bucket #2
type BucketDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketDatas []*BucketData `protobuf:"bytes,1,rep,name=bucket_datas,json=bucketDatas,proto3" json:"bucket_datas,omitempty"`
}

func (x *BucketDataResponse) Reset() {
	*x = BucketDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketDataResponse) ProtoMessage() {}

func (x *BucketDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketDataResponse.ProtoReflect.Descriptor instead.
func (*BucketDataResponse) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{8}
}

func (x *BucketDataResponse) GetBucketDatas() []*BucketData {
	if x != nil {
		return x.BucketDatas
	}
	return nil
}

type ExternalBucketDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketId []uint64 `protobuf:"varint,1,rep,packed,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
}

func (x *ExternalBucketDataRequest) Reset() {
	*x = ExternalBucketDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalBucketDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalBucketDataRequest) ProtoMessage() {}

func (x *ExternalBucketDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalBucketDataRequest.ProtoReflect.Descriptor instead.
func (*ExternalBucketDataRequest) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{9}
}

func (x *ExternalBucketDataRequest) GetBucketId() []uint64 {
	if x != nil {
		return x.BucketId
	}
	return nil
}

type ExternalBucketDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketCount            uint64                `protobuf:"varint,1,opt,name=bucket_count,json=bucketCount,proto3" json:"bucket_count,omitempty"`
	IndiscernibilityDegree uint64                `protobuf:"varint,2,opt,name=indiscernibility_degree,json=indiscernibilityDegree,proto3" json:"indiscernibility_degree,omitempty"`
	Data                   []*ExternalBucketData `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	MetaInfo               string                `protobuf:"bytes,4,opt,name=meta_info,json=metaInfo,proto3" json:"meta_info,omitempty"` // json string
}

func (x *ExternalBucketDataResponse) Reset() {
	*x = ExternalBucketDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalBucketDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalBucketDataResponse) ProtoMessage() {}

func (x *ExternalBucketDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalBucketDataResponse.ProtoReflect.Descriptor instead.
func (*ExternalBucketDataResponse) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{10}
}

func (x *ExternalBucketDataResponse) GetBucketCount() uint64 {
	if x != nil {
		return x.BucketCount
	}
	return 0
}

func (x *ExternalBucketDataResponse) GetIndiscernibilityDegree() uint64 {
	if x != nil {
		return x.IndiscernibilityDegree
	}
	return 0
}

func (x *ExternalBucketDataResponse) GetData() []*ExternalBucketData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExternalBucketDataResponse) GetMetaInfo() string {
	if x != nil {
		return x.MetaInfo
	}
	return ""
}

type ExternalBucketData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ExternalBucketData) Reset() {
	*x = ExternalBucketData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalBucketData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalBucketData) ProtoMessage() {}

func (x *ExternalBucketData) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalBucketData.ProtoReflect.Descriptor instead.
func (*ExternalBucketData) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{11}
}

func (x *ExternalBucketData) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId uint64              `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Token     string              `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	PartyInfo *protobuf.PartyInfo `protobuf:"bytes,3,opt,name=party_info,json=partyInfo,proto3" json:"party_info,omitempty"`
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{12}
}

func (x *ValidateTokenRequest) GetServiceId() uint64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateTokenRequest) GetPartyInfo() *protobuf.PartyInfo {
	if x != nil {
		return x.PartyInfo
	}
	return nil
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{13}
}

func (x *ValidateTokenResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GrpcGWDeployRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to DeployMode:
	//	*GrpcGWDeployRequest_Mysql
	//	*GrpcGWDeployRequest_Api
	//	*GrpcGWDeployRequest_Vtable
	DeployMode isGrpcGWDeployRequest_DeployMode `protobuf_oneof:"deploy_mode"`
}

func (x *GrpcGWDeployRequest) Reset() {
	*x = GrpcGWDeployRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcGWDeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcGWDeployRequest) ProtoMessage() {}

func (x *GrpcGWDeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcGWDeployRequest.ProtoReflect.Descriptor instead.
func (*GrpcGWDeployRequest) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{14}
}

func (m *GrpcGWDeployRequest) GetDeployMode() isGrpcGWDeployRequest_DeployMode {
	if m != nil {
		return m.DeployMode
	}
	return nil
}

func (x *GrpcGWDeployRequest) GetMysql() *MysqlDeploy {
	if x, ok := x.GetDeployMode().(*GrpcGWDeployRequest_Mysql); ok {
		return x.Mysql
	}
	return nil
}

func (x *GrpcGWDeployRequest) GetApi() *ExternalApiDeploy {
	if x, ok := x.GetDeployMode().(*GrpcGWDeployRequest_Api); ok {
		return x.Api
	}
	return nil
}

func (x *GrpcGWDeployRequest) GetVtable() *VtableDeploy {
	if x, ok := x.GetDeployMode().(*GrpcGWDeployRequest_Vtable); ok {
		return x.Vtable
	}
	return nil
}

type isGrpcGWDeployRequest_DeployMode interface {
	isGrpcGWDeployRequest_DeployMode()
}

type GrpcGWDeployRequest_Mysql struct {
	Mysql *MysqlDeploy `protobuf:"bytes,1,opt,name=mysql,proto3,oneof"`
}

type GrpcGWDeployRequest_Api struct {
	Api *ExternalApiDeploy `protobuf:"bytes,2,opt,name=api,proto3,oneof"`
}

type GrpcGWDeployRequest_Vtable struct {
	Vtable *VtableDeploy `protobuf:"bytes,3,opt,name=vtable,proto3,oneof"`
}

func (*GrpcGWDeployRequest_Mysql) isGrpcGWDeployRequest_DeployMode() {}

func (*GrpcGWDeployRequest_Api) isGrpcGWDeployRequest_DeployMode() {}

func (*GrpcGWDeployRequest_Vtable) isGrpcGWDeployRequest_DeployMode() {}

type MysqlDeploy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContextStr             string   `protobuf:"bytes,1,opt,name=context_str,json=contextStr,proto3" json:"context_str,omitempty"`                                     // web端调用时使用，json string
	OriginDataPath         string   `protobuf:"bytes,2,opt,name=origin_data_path,json=originDataPath,proto3" json:"origin_data_path,omitempty"`                       // web端调用时使用，原始数据路径 e.g. db1.bank_0109
	OutputDataPath         string   `protobuf:"bytes,3,opt,name=output_data_path,json=outputDataPath,proto3" json:"output_data_path,omitempty"`                       // web端调用时使用，预处理后可存放的数据路径  e.g. sudo_output.bank_0109
	IndiscernibilityDegree string   `protobuf:"bytes,4,opt,name=indiscernibility_degree,json=indiscernibilityDegree,proto3" json:"indiscernibility_degree,omitempty"` // web端调用时使用，不可区分度
	KeyColumns             []string `protobuf:"bytes,5,rep,name=key_columns,json=keyColumns,proto3" json:"key_columns,omitempty"`                                     // web端调用时使用，匹配列
}

func (x *MysqlDeploy) Reset() {
	*x = MysqlDeploy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MysqlDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlDeploy) ProtoMessage() {}

func (x *MysqlDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlDeploy.ProtoReflect.Descriptor instead.
func (*MysqlDeploy) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{15}
}

func (x *MysqlDeploy) GetContextStr() string {
	if x != nil {
		return x.ContextStr
	}
	return ""
}

func (x *MysqlDeploy) GetOriginDataPath() string {
	if x != nil {
		return x.OriginDataPath
	}
	return ""
}

func (x *MysqlDeploy) GetOutputDataPath() string {
	if x != nil {
		return x.OutputDataPath
	}
	return ""
}

func (x *MysqlDeploy) GetIndiscernibilityDegree() string {
	if x != nil {
		return x.IndiscernibilityDegree
	}
	return ""
}

func (x *MysqlDeploy) GetKeyColumns() []string {
	if x != nil {
		return x.KeyColumns
	}
	return nil
}

type ExternalApiDeploy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url  string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Types that are assignable to AuthMethod:
	//	*ExternalApiDeploy_NoAuth
	//	*ExternalApiDeploy_BasicAuth
	AuthMethod isExternalApiDeploy_AuthMethod `protobuf_oneof:"auth_method"`
}

func (x *ExternalApiDeploy) Reset() {
	*x = ExternalApiDeploy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalApiDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalApiDeploy) ProtoMessage() {}

func (x *ExternalApiDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalApiDeploy.ProtoReflect.Descriptor instead.
func (*ExternalApiDeploy) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{16}
}

func (x *ExternalApiDeploy) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ExternalApiDeploy) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (m *ExternalApiDeploy) GetAuthMethod() isExternalApiDeploy_AuthMethod {
	if m != nil {
		return m.AuthMethod
	}
	return nil
}

func (x *ExternalApiDeploy) GetNoAuth() *NoAuth {
	if x, ok := x.GetAuthMethod().(*ExternalApiDeploy_NoAuth); ok {
		return x.NoAuth
	}
	return nil
}

func (x *ExternalApiDeploy) GetBasicAuth() *BasicAuth {
	if x, ok := x.GetAuthMethod().(*ExternalApiDeploy_BasicAuth); ok {
		return x.BasicAuth
	}
	return nil
}

type isExternalApiDeploy_AuthMethod interface {
	isExternalApiDeploy_AuthMethod()
}

type ExternalApiDeploy_NoAuth struct {
	NoAuth *NoAuth `protobuf:"bytes,3,opt,name=no_auth,json=noAuth,proto3,oneof"`
}

type ExternalApiDeploy_BasicAuth struct {
	BasicAuth *BasicAuth `protobuf:"bytes,4,opt,name=basic_auth,json=basicAuth,proto3,oneof"`
}

func (*ExternalApiDeploy_NoAuth) isExternalApiDeploy_AuthMethod() {}

func (*ExternalApiDeploy_BasicAuth) isExternalApiDeploy_AuthMethod() {}

type VtableDeploy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VtableId uint64 `protobuf:"varint,1,opt,name=vtable_id,json=vtableId,proto3" json:"vtable_id,omitempty"`
}

func (x *VtableDeploy) Reset() {
	*x = VtableDeploy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VtableDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VtableDeploy) ProtoMessage() {}

func (x *VtableDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VtableDeploy.ProtoReflect.Descriptor instead.
func (*VtableDeploy) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{17}
}

func (x *VtableDeploy) GetVtableId() uint64 {
	if x != nil {
		return x.VtableId
	}
	return 0
}

type NoAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoAuth) Reset() {
	*x = NoAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoAuth) ProtoMessage() {}

func (x *NoAuth) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoAuth.ProtoReflect.Descriptor instead.
func (*NoAuth) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{18}
}

type BasicAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *BasicAuth) Reset() {
	*x = BasicAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicAuth) ProtoMessage() {}

func (x *BasicAuth) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicAuth.ProtoReflect.Descriptor instead.
func (*BasicAuth) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{19}
}

func (x *BasicAuth) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BasicAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GrpcGWDeployResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GrpcGWDeployResponse) Reset() {
	*x = GrpcGWDeployResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcGWDeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcGWDeployResponse) ProtoMessage() {}

func (x *GrpcGWDeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcGWDeployResponse.ProtoReflect.Descriptor instead.
func (*GrpcGWDeployResponse) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{20}
}

func (x *GrpcGWDeployResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ServerClientSyncRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId uint64              `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	PartyInfo *protobuf.PartyInfo `protobuf:"bytes,2,opt,name=party_info,json=partyInfo,proto3" json:"party_info,omitempty"` // 仅在client call算子时传入，算子call paas server时不传
}

func (x *ServerClientSyncRequest) Reset() {
	*x = ServerClientSyncRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerClientSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerClientSyncRequest) ProtoMessage() {}

func (x *ServerClientSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerClientSyncRequest.ProtoReflect.Descriptor instead.
func (*ServerClientSyncRequest) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{21}
}

func (x *ServerClientSyncRequest) GetServiceId() uint64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *ServerClientSyncRequest) GetPartyInfo() *protobuf.PartyInfo {
	if x != nil {
		return x.PartyInfo
	}
	return nil
}

type ServerClientSyncResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status SyncStatus `protobuf:"varint,1,opt,name=status,proto3,enum=sudo.protobuf.service.SyncStatus" json:"status,omitempty"`
	// deploy进度，返回百分比
	Progress float32 `protobuf:"fixed32,2,opt,name=progress,proto3" json:"progress,omitempty"`
	// deploy失败时才有值
	ErrMsg                 string         `protobuf:"bytes,3,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	IndiscernibilityDegree uint64         `protobuf:"varint,4,opt,name=indiscernibility_degree,json=indiscernibilityDegree,proto3" json:"indiscernibility_degree,omitempty"`
	KeyColumns             []string       `protobuf:"bytes,5,rep,name=key_columns,json=keyColumns,proto3" json:"key_columns,omitempty"`
	LabelColumns           []string       `protobuf:"bytes,6,rep,name=label_columns,json=labelColumns,proto3" json:"label_columns,omitempty"`
	Type                   enums.SVCType  `protobuf:"varint,7,opt,name=type,proto3,enum=sudo.protobuf.service.enums.SVCType" json:"type,omitempty"`                          // deploy mode, see deploy_mode definition for more details
	DataMode               enums.DataMode `protobuf:"varint,8,opt,name=data_mode,json=dataMode,proto3,enum=sudo.protobuf.service.enums.DataMode" json:"data_mode,omitempty"` // data mode, see data_mode definition for more details
	// 存放其余业务属性
	Context map[string]string `protobuf:"bytes,9,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ServerClientSyncResponse) Reset() {
	*x = ServerClientSyncResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_service_online_service_common_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerClientSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerClientSyncResponse) ProtoMessage() {}

func (x *ServerClientSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_service_online_service_common_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerClientSyncResponse.ProtoReflect.Descriptor instead.
func (*ServerClientSyncResponse) Descriptor() ([]byte, []int) {
	return file_sudo_service_online_service_common_proto_rawDescGZIP(), []int{22}
}

func (x *ServerClientSyncResponse) GetStatus() SyncStatus {
	if x != nil {
		return x.Status
	}
	return SyncStatus_UNKNOWN
}

func (x *ServerClientSyncResponse) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ServerClientSyncResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *ServerClientSyncResponse) GetIndiscernibilityDegree() uint64 {
	if x != nil {
		return x.IndiscernibilityDegree
	}
	return 0
}

func (x *ServerClientSyncResponse) GetKeyColumns() []string {
	if x != nil {
		return x.KeyColumns
	}
	return nil
}

func (x *ServerClientSyncResponse) GetLabelColumns() []string {
	if x != nil {
		return x.LabelColumns
	}
	return nil
}

func (x *ServerClientSyncResponse) GetType() enums.SVCType {
	if x != nil {
		return x.Type
	}
	return enums.SVCType_UNKNOWN_TYPE
}

func (x *ServerClientSyncResponse) GetDataMode() enums.DataMode {
	if x != nil {
		return x.DataMode
	}
	return enums.DataMode_UNKNOWN_DATA_MODE
}

func (x *ServerClientSyncResponse) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

var File_sudo_service_online_service_common_proto protoreflect.FileDescriptor

var file_sudo_service_online_service_common_proto_rawDesc = []byte{
	0x0a, 0x28, 0x73, 0x75, 0x64, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x73, 0x75, 0x64, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x1a, 0x26, 0x73, 0x75, 0x64, 0x6f, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x5f, 0x61, 0x64,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x5f, 0x61, 0x64, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x29, 0x73, 0x75, 0x64, 0x6f, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f, 0x6f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x19,
	0x0a, 0x08, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x61, 0x72, 0x74, 0x79, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x12, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22,
	0x72, 0x0a, 0x11, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x08, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x22, 0x99, 0x01, 0x0a, 0x1b, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x45, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x74,
	0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73,
	0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x69, 0x6e, 0x66,
	0x72, 0x61, 0x5f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0xab, 0x01, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21,
	0x0a, 0x0c, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x45, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x5f, 0x61, 0x64, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x70,
	0x61, 0x72, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x74, 0x78, 0x5f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6f, 0x74,
	0x78, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x8d, 0x05,
	0x0a, 0x1c, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21,
	0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x37, 0x0a, 0x17, 0x69, 0x6e, 0x64, 0x69, 0x73, 0x63, 0x65,
	0x72, 0x6e, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x16, 0x69, 0x6e, 0x64, 0x69, 0x73, 0x63, 0x65, 0x72,
	0x6e, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x6b, 0x65, 0x79, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0a, 0x6b, 0x65, 0x79, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12,
	0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0c, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x24, 0x0a,
	0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x69, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x49, 0x64, 0x12, 0x42, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x38, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x6e,
	0x75, 0x6d, 0x73, 0x2e, 0x53, 0x56, 0x43, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x42, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x6e, 0x75,
	0x6d, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74,
	0x61, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x5a, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x40, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53,
	0x79, 0x6e, 0x63, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x1a, 0x3a, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x19, 0x0a,
	0x03, 0x52, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x3c, 0x0a, 0x0a, 0x42, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x6f, 0x77,
	0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x5a, 0x0a, 0x12, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0c,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0b, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x73, 0x22, 0x38, 0x0a, 0x19, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x42, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x04, 0x52, 0x08, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x22, 0xd4, 0x01, 0x0a,
	0x1a, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0b, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x37,
	0x0a, 0x17, 0x69, 0x6e, 0x64, 0x69, 0x73, 0x63, 0x65, 0x72, 0x6e, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x5f, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x16, 0x69, 0x6e, 0x64, 0x69, 0x73, 0x63, 0x65, 0x72, 0x6e, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65, 0x12, 0x3d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x28, 0x0a, 0x12, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x42,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x92, 0x01,
	0x0a, 0x14, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x45, 0x0a, 0x0a, 0x70,
	0x61, 0x72, 0x74, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x69, 0x6e, 0x66, 0x72, 0x61, 0x5f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x50, 0x61,
	0x72, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x27, 0x0a, 0x15, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0xdd, 0x01, 0x0a, 0x13,
	0x47, 0x72, 0x70, 0x63, 0x47, 0x57, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x05, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x79, 0x73, 0x71, 0x6c,
	0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x48, 0x00, 0x52, 0x05, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x12,
	0x3c, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x73,
	0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x41, 0x70, 0x69,
	0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x48, 0x00, 0x52, 0x03, 0x61, 0x70, 0x69, 0x12, 0x3d, 0x0a,
	0x06, 0x76, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x48, 0x00, 0x52, 0x06, 0x76, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x0d, 0x0a, 0x0b,
	0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0xdc, 0x01, 0x0a, 0x0b,
	0x4d, 0x79, 0x73, 0x71, 0x6c, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x53, 0x74, 0x72, 0x12, 0x28, 0x0a, 0x10,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x50, 0x61, 0x74, 0x68, 0x12, 0x28, 0x0a, 0x10, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x44, 0x61, 0x74, 0x61, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x37, 0x0a, 0x17, 0x69, 0x6e, 0x64, 0x69, 0x73, 0x63, 0x65, 0x72, 0x6e, 0x69, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x16, 0x69, 0x6e, 0x64, 0x69, 0x73, 0x63, 0x65, 0x72, 0x6e, 0x69, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6b, 0x65, 0x79,
	0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a,
	0x6b, 0x65, 0x79, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x22, 0xc5, 0x01, 0x0a, 0x11, 0x45,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x41, 0x70, 0x69, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x38, 0x0a, 0x07, 0x6e, 0x6f, 0x5f, 0x61, 0x75, 0x74,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x4e, 0x6f, 0x41, 0x75, 0x74, 0x68, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x6f, 0x41, 0x75, 0x74, 0x68,
	0x12, 0x41, 0x0a, 0x0a, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x48, 0x00, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x41,
	0x75, 0x74, 0x68, 0x42, 0x0d, 0x0a, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x22, 0x2b, 0x0a, 0x0c, 0x56, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x76, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x22,
	0x08, 0x0a, 0x06, 0x4e, 0x6f, 0x41, 0x75, 0x74, 0x68, 0x22, 0x43, 0x0a, 0x09, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x28,
	0x0a, 0x14, 0x47, 0x72, 0x70, 0x63, 0x47, 0x57, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x7f, 0x0a, 0x17, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x45, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x5f, 0x61, 0x64, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09,
	0x70, 0x61, 0x72, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x9b, 0x04, 0x0a, 0x18, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53,
	0x79, 0x6e, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x17, 0x0a,
	0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x37, 0x0a, 0x17, 0x69, 0x6e, 0x64, 0x69, 0x73, 0x63,
	0x65, 0x72, 0x6e, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x65, 0x67, 0x72, 0x65,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x16, 0x69, 0x6e, 0x64, 0x69, 0x73, 0x63, 0x65,
	0x72, 0x6e, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x6b, 0x65, 0x79, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6b, 0x65, 0x79, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73,
	0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x43, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x38, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x6e, 0x75, 0x6d,
	0x73, 0x2e, 0x53, 0x56, 0x43, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x42, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x25, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x4d,
	0x6f, 0x64, 0x65, 0x12, 0x56, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x09,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x1a, 0x3a, 0x0a, 0x0c, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x4f, 0x0a, 0x0a, 0x53, 0x79, 0x6e, 0x63, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x49, 0x4e, 0x47, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x0a,
	0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x55, 0x50,
	0x44, 0x41, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x32, 0x79, 0x0a, 0x14, 0x46, 0x75, 0x72, 0x6e,
	0x61, 0x63, 0x65, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x61, 0x0a, 0x0a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x28,
	0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0xfe, 0x01, 0x0a, 0x1a, 0x46, 0x75, 0x72, 0x6e, 0x61, 0x63, 0x65, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x12, 0x61, 0x0a, 0x0a, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x28, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x73, 0x75, 0x64,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7d, 0x0a, 0x1a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x4f, 0x70, 0x43, 0x61, 0x6c, 0x6c, 0x50,
	0x61, 0x61, 0x73, 0x12, 0x2e, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x98, 0x01, 0x0a, 0x15, 0x4f, 0x70, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x7f,
	0x0a, 0x14, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x32, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53,
	0x79, 0x6e, 0x63, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x73, 0x75, 0x64,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sudo_service_online_service_common_proto_rawDescOnce sync.Once
	file_sudo_service_online_service_common_proto_rawDescData = file_sudo_service_online_service_common_proto_rawDesc
)

func file_sudo_service_online_service_common_proto_rawDescGZIP() []byte {
	file_sudo_service_online_service_common_proto_rawDescOnce.Do(func() {
		file_sudo_service_online_service_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_sudo_service_online_service_common_proto_rawDescData)
	})
	return file_sudo_service_online_service_common_proto_rawDescData
}

var file_sudo_service_online_service_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sudo_service_online_service_common_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_sudo_service_online_service_common_proto_goTypes = []interface{}{
	(SyncStatus)(0),                      // 0: sudo.protobuf.service.SyncStatus
	(*CheckTokenRequest)(nil),            // 1: sudo.protobuf.service.CheckTokenRequest
	(*CheckTokenResponse)(nil),           // 2: sudo.protobuf.service.CheckTokenResponse
	(*BucketDataRequest)(nil),            // 3: sudo.protobuf.service.BucketDataRequest
	(*SyncClientDeployInfoRequest)(nil),  // 4: sudo.protobuf.service.SyncClientDeployInfoRequest
	(*ClientInfo)(nil),                   // 5: sudo.protobuf.service.ClientInfo
	(*SyncClientDeployInfoResponse)(nil), // 6: sudo.protobuf.service.SyncClientDeployInfoResponse
	(*Row)(nil),                          // 7: sudo.protobuf.service.Row
	(*BucketData)(nil),                   // 8: sudo.protobuf.service.BucketData
	(*BucketDataResponse)(nil),           // 9: sudo.protobuf.service.BucketDataResponse
	(*ExternalBucketDataRequest)(nil),    // 10: sudo.protobuf.service.ExternalBucketDataRequest
	(*ExternalBucketDataResponse)(nil),   // 11: sudo.protobuf.service.ExternalBucketDataResponse
	(*ExternalBucketData)(nil),           // 12: sudo.protobuf.service.ExternalBucketData
	(*ValidateTokenRequest)(nil),         // 13: sudo.protobuf.service.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),        // 14: sudo.protobuf.service.ValidateTokenResponse
	(*GrpcGWDeployRequest)(nil),          // 15: sudo.protobuf.service.GrpcGWDeployRequest
	(*MysqlDeploy)(nil),                  // 16: sudo.protobuf.service.MysqlDeploy
	(*ExternalApiDeploy)(nil),            // 17: sudo.protobuf.service.ExternalApiDeploy
	(*VtableDeploy)(nil),                 // 18: sudo.protobuf.service.VtableDeploy
	(*NoAuth)(nil),                       // 19: sudo.protobuf.service.NoAuth
	(*BasicAuth)(nil),                    // 20: sudo.protobuf.service.BasicAuth
	(*GrpcGWDeployResponse)(nil),         // 21: sudo.protobuf.service.GrpcGWDeployResponse
	(*ServerClientSyncRequest)(nil),      // 22: sudo.protobuf.service.ServerClientSyncRequest
	(*ServerClientSyncResponse)(nil),     // 23: sudo.protobuf.service.ServerClientSyncResponse
	nil,                                  // 24: sudo.protobuf.service.SyncClientDeployInfoResponse.ContextEntry
	nil,                                  // 25: sudo.protobuf.service.ServerClientSyncResponse.ContextEntry
	(*protobuf.PartyInfo)(nil),           // 26: sudo.protobuf.infra_adapter.PartyInfo
	(enums.SVCType)(0),                   // 27: sudo.protobuf.service.enums.SVCType
	(enums.DataMode)(0),                  // 28: sudo.protobuf.service.enums.DataMode
}
var file_sudo_service_online_service_common_proto_depIdxs = []int32{
	26, // 0: sudo.protobuf.service.SyncClientDeployInfoRequest.party_info:type_name -> sudo.protobuf.infra_adapter.PartyInfo
	26, // 1: sudo.protobuf.service.ClientInfo.party_info:type_name -> sudo.protobuf.infra_adapter.PartyInfo
	0,  // 2: sudo.protobuf.service.SyncClientDeployInfoResponse.status:type_name -> sudo.protobuf.service.SyncStatus
	5,  // 3: sudo.protobuf.service.SyncClientDeployInfoResponse.client_info:type_name -> sudo.protobuf.service.ClientInfo
	27, // 4: sudo.protobuf.service.SyncClientDeployInfoResponse.type:type_name -> sudo.protobuf.service.enums.SVCType
	28, // 5: sudo.protobuf.service.SyncClientDeployInfoResponse.data_mode:type_name -> sudo.protobuf.service.enums.DataMode
	24, // 6: sudo.protobuf.service.SyncClientDeployInfoResponse.context:type_name -> sudo.protobuf.service.SyncClientDeployInfoResponse.ContextEntry
	7,  // 7: sudo.protobuf.service.BucketData.rows:type_name -> sudo.protobuf.service.Row
	8,  // 8: sudo.protobuf.service.BucketDataResponse.bucket_datas:type_name -> sudo.protobuf.service.BucketData
	12, // 9: sudo.protobuf.service.ExternalBucketDataResponse.data:type_name -> sudo.protobuf.service.ExternalBucketData
	26, // 10: sudo.protobuf.service.ValidateTokenRequest.party_info:type_name -> sudo.protobuf.infra_adapter.PartyInfo
	16, // 11: sudo.protobuf.service.GrpcGWDeployRequest.mysql:type_name -> sudo.protobuf.service.MysqlDeploy
	17, // 12: sudo.protobuf.service.GrpcGWDeployRequest.api:type_name -> sudo.protobuf.service.ExternalApiDeploy
	18, // 13: sudo.protobuf.service.GrpcGWDeployRequest.vtable:type_name -> sudo.protobuf.service.VtableDeploy
	19, // 14: sudo.protobuf.service.ExternalApiDeploy.no_auth:type_name -> sudo.protobuf.service.NoAuth
	20, // 15: sudo.protobuf.service.ExternalApiDeploy.basic_auth:type_name -> sudo.protobuf.service.BasicAuth
	26, // 16: sudo.protobuf.service.ServerClientSyncRequest.party_info:type_name -> sudo.protobuf.infra_adapter.PartyInfo
	0,  // 17: sudo.protobuf.service.ServerClientSyncResponse.status:type_name -> sudo.protobuf.service.SyncStatus
	27, // 18: sudo.protobuf.service.ServerClientSyncResponse.type:type_name -> sudo.protobuf.service.enums.SVCType
	28, // 19: sudo.protobuf.service.ServerClientSyncResponse.data_mode:type_name -> sudo.protobuf.service.enums.DataMode
	25, // 20: sudo.protobuf.service.ServerClientSyncResponse.context:type_name -> sudo.protobuf.service.ServerClientSyncResponse.ContextEntry
	1,  // 21: sudo.protobuf.service.FurnaceOnlineService.CheckToken:input_type -> sudo.protobuf.service.CheckTokenRequest
	3,  // 22: sudo.protobuf.service.FurnaceOnlineServiceCommon.BucketData:input_type -> sudo.protobuf.service.BucketDataRequest
	22, // 23: sudo.protobuf.service.FurnaceOnlineServiceCommon.ServerClientSyncOpCallPaas:input_type -> sudo.protobuf.service.ServerClientSyncRequest
	4,  // 24: sudo.protobuf.service.OpOnlineServiceCommon.SyncClientDeployInfo:input_type -> sudo.protobuf.service.SyncClientDeployInfoRequest
	2,  // 25: sudo.protobuf.service.FurnaceOnlineService.CheckToken:output_type -> sudo.protobuf.service.CheckTokenResponse
	9,  // 26: sudo.protobuf.service.FurnaceOnlineServiceCommon.BucketData:output_type -> sudo.protobuf.service.BucketDataResponse
	23, // 27: sudo.protobuf.service.FurnaceOnlineServiceCommon.ServerClientSyncOpCallPaas:output_type -> sudo.protobuf.service.ServerClientSyncResponse
	6,  // 28: sudo.protobuf.service.OpOnlineServiceCommon.SyncClientDeployInfo:output_type -> sudo.protobuf.service.SyncClientDeployInfoResponse
	25, // [25:29] is the sub-list for method output_type
	21, // [21:25] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_sudo_service_online_service_common_proto_init() }
func file_sudo_service_online_service_common_proto_init() {
	if File_sudo_service_online_service_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sudo_service_online_service_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncClientDeployInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncClientDeployInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalBucketDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalBucketDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalBucketData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcGWDeployRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MysqlDeploy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalApiDeploy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VtableDeploy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcGWDeployResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerClientSyncRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_service_online_service_common_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerClientSyncResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sudo_service_online_service_common_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*GrpcGWDeployRequest_Mysql)(nil),
		(*GrpcGWDeployRequest_Api)(nil),
		(*GrpcGWDeployRequest_Vtable)(nil),
	}
	file_sudo_service_online_service_common_proto_msgTypes[16].OneofWrappers = []interface{}{
		(*ExternalApiDeploy_NoAuth)(nil),
		(*ExternalApiDeploy_BasicAuth)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sudo_service_online_service_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_sudo_service_online_service_common_proto_goTypes,
		DependencyIndexes: file_sudo_service_online_service_common_proto_depIdxs,
		EnumInfos:         file_sudo_service_online_service_common_proto_enumTypes,
		MessageInfos:      file_sudo_service_online_service_common_proto_msgTypes,
	}.Build()
	File_sudo_service_online_service_common_proto = out.File
	file_sudo_service_online_service_common_proto_rawDesc = nil
	file_sudo_service_online_service_common_proto_goTypes = nil
	file_sudo_service_online_service_common_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FurnaceOnlineServiceClient is the client API for FurnaceOnlineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FurnaceOnlineServiceClient interface {
	CheckToken(ctx context.Context, in *CheckTokenRequest, opts ...grpc.CallOption) (*CheckTokenResponse, error)
}

type furnaceOnlineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFurnaceOnlineServiceClient(cc grpc.ClientConnInterface) FurnaceOnlineServiceClient {
	return &furnaceOnlineServiceClient{cc}
}

func (c *furnaceOnlineServiceClient) CheckToken(ctx context.Context, in *CheckTokenRequest, opts ...grpc.CallOption) (*CheckTokenResponse, error) {
	out := new(CheckTokenResponse)
	err := c.cc.Invoke(ctx, "/sudo.protobuf.service.FurnaceOnlineService/CheckToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FurnaceOnlineServiceServer is the server API for FurnaceOnlineService service.
type FurnaceOnlineServiceServer interface {
	CheckToken(context.Context, *CheckTokenRequest) (*CheckTokenResponse, error)
}

// UnimplementedFurnaceOnlineServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFurnaceOnlineServiceServer struct {
}

func (*UnimplementedFurnaceOnlineServiceServer) CheckToken(context.Context, *CheckTokenRequest) (*CheckTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckToken not implemented")
}

func RegisterFurnaceOnlineServiceServer(s *grpc.Server, srv FurnaceOnlineServiceServer) {
	s.RegisterService(&_FurnaceOnlineService_serviceDesc, srv)
}

func _FurnaceOnlineService_CheckToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FurnaceOnlineServiceServer).CheckToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sudo.protobuf.service.FurnaceOnlineService/CheckToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FurnaceOnlineServiceServer).CheckToken(ctx, req.(*CheckTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FurnaceOnlineService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sudo.protobuf.service.FurnaceOnlineService",
	HandlerType: (*FurnaceOnlineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckToken",
			Handler:    _FurnaceOnlineService_CheckToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sudo/service/online_service_common.proto",
}

// FurnaceOnlineServiceCommonClient is the client API for FurnaceOnlineServiceCommon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FurnaceOnlineServiceCommonClient interface {
	// 算子call paas go，paas后端从外部api 获取数据并返回给算子
	BucketData(ctx context.Context, in *BucketDataRequest, opts ...grpc.CallOption) (*BucketDataResponse, error)
	//    client -> client operator -> server operator -> paas server
	//           <- client operator <- server operator <- (返回结果)
	// 用于以上链路同步在线服务client 和server的通用数据
	ServerClientSyncOpCallPaas(ctx context.Context, in *ServerClientSyncRequest, opts ...grpc.CallOption) (*ServerClientSyncResponse, error)
}

type furnaceOnlineServiceCommonClient struct {
	cc grpc.ClientConnInterface
}

func NewFurnaceOnlineServiceCommonClient(cc grpc.ClientConnInterface) FurnaceOnlineServiceCommonClient {
	return &furnaceOnlineServiceCommonClient{cc}
}

func (c *furnaceOnlineServiceCommonClient) BucketData(ctx context.Context, in *BucketDataRequest, opts ...grpc.CallOption) (*BucketDataResponse, error) {
	out := new(BucketDataResponse)
	err := c.cc.Invoke(ctx, "/sudo.protobuf.service.FurnaceOnlineServiceCommon/BucketData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *furnaceOnlineServiceCommonClient) ServerClientSyncOpCallPaas(ctx context.Context, in *ServerClientSyncRequest, opts ...grpc.CallOption) (*ServerClientSyncResponse, error) {
	out := new(ServerClientSyncResponse)
	err := c.cc.Invoke(ctx, "/sudo.protobuf.service.FurnaceOnlineServiceCommon/ServerClientSyncOpCallPaas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FurnaceOnlineServiceCommonServer is the server API for FurnaceOnlineServiceCommon service.
type FurnaceOnlineServiceCommonServer interface {
	// 算子call paas go，paas后端从外部api 获取数据并返回给算子
	BucketData(context.Context, *BucketDataRequest) (*BucketDataResponse, error)
	//    client -> client operator -> server operator -> paas server
	//           <- client operator <- server operator <- (返回结果)
	// 用于以上链路同步在线服务client 和server的通用数据
	ServerClientSyncOpCallPaas(context.Context, *ServerClientSyncRequest) (*ServerClientSyncResponse, error)
}

// UnimplementedFurnaceOnlineServiceCommonServer can be embedded to have forward compatible implementations.
type UnimplementedFurnaceOnlineServiceCommonServer struct {
}

func (*UnimplementedFurnaceOnlineServiceCommonServer) BucketData(context.Context, *BucketDataRequest) (*BucketDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BucketData not implemented")
}
func (*UnimplementedFurnaceOnlineServiceCommonServer) ServerClientSyncOpCallPaas(context.Context, *ServerClientSyncRequest) (*ServerClientSyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerClientSyncOpCallPaas not implemented")
}

func RegisterFurnaceOnlineServiceCommonServer(s *grpc.Server, srv FurnaceOnlineServiceCommonServer) {
	s.RegisterService(&_FurnaceOnlineServiceCommon_serviceDesc, srv)
}

func _FurnaceOnlineServiceCommon_BucketData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BucketDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FurnaceOnlineServiceCommonServer).BucketData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sudo.protobuf.service.FurnaceOnlineServiceCommon/BucketData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FurnaceOnlineServiceCommonServer).BucketData(ctx, req.(*BucketDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FurnaceOnlineServiceCommon_ServerClientSyncOpCallPaas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerClientSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FurnaceOnlineServiceCommonServer).ServerClientSyncOpCallPaas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sudo.protobuf.service.FurnaceOnlineServiceCommon/ServerClientSyncOpCallPaas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FurnaceOnlineServiceCommonServer).ServerClientSyncOpCallPaas(ctx, req.(*ServerClientSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FurnaceOnlineServiceCommon_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sudo.protobuf.service.FurnaceOnlineServiceCommon",
	HandlerType: (*FurnaceOnlineServiceCommonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BucketData",
			Handler:    _FurnaceOnlineServiceCommon_BucketData_Handler,
		},
		{
			MethodName: "ServerClientSyncOpCallPaas",
			Handler:    _FurnaceOnlineServiceCommon_ServerClientSyncOpCallPaas_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sudo/service/online_service_common.proto",
}

// OpOnlineServiceCommonClient is the client API for OpOnlineServiceCommon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OpOnlineServiceCommonClient interface {
	// 同步client端部署结果，包括状态码、进度、分桶数、匹配列、异常信息
	SyncClientDeployInfo(ctx context.Context, in *SyncClientDeployInfoRequest, opts ...grpc.CallOption) (*SyncClientDeployInfoResponse, error)
}

type opOnlineServiceCommonClient struct {
	cc grpc.ClientConnInterface
}

func NewOpOnlineServiceCommonClient(cc grpc.ClientConnInterface) OpOnlineServiceCommonClient {
	return &opOnlineServiceCommonClient{cc}
}

func (c *opOnlineServiceCommonClient) SyncClientDeployInfo(ctx context.Context, in *SyncClientDeployInfoRequest, opts ...grpc.CallOption) (*SyncClientDeployInfoResponse, error) {
	out := new(SyncClientDeployInfoResponse)
	err := c.cc.Invoke(ctx, "/sudo.protobuf.service.OpOnlineServiceCommon/SyncClientDeployInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpOnlineServiceCommonServer is the server API for OpOnlineServiceCommon service.
type OpOnlineServiceCommonServer interface {
	// 同步client端部署结果，包括状态码、进度、分桶数、匹配列、异常信息
	SyncClientDeployInfo(context.Context, *SyncClientDeployInfoRequest) (*SyncClientDeployInfoResponse, error)
}

// UnimplementedOpOnlineServiceCommonServer can be embedded to have forward compatible implementations.
type UnimplementedOpOnlineServiceCommonServer struct {
}

func (*UnimplementedOpOnlineServiceCommonServer) SyncClientDeployInfo(context.Context, *SyncClientDeployInfoRequest) (*SyncClientDeployInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncClientDeployInfo not implemented")
}

func RegisterOpOnlineServiceCommonServer(s *grpc.Server, srv OpOnlineServiceCommonServer) {
	s.RegisterService(&_OpOnlineServiceCommon_serviceDesc, srv)
}

func _OpOnlineServiceCommon_SyncClientDeployInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncClientDeployInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpOnlineServiceCommonServer).SyncClientDeployInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sudo.protobuf.service.OpOnlineServiceCommon/SyncClientDeployInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpOnlineServiceCommonServer).SyncClientDeployInfo(ctx, req.(*SyncClientDeployInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OpOnlineServiceCommon_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sudo.protobuf.service.OpOnlineServiceCommon",
	HandlerType: (*OpOnlineServiceCommonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncClientDeployInfo",
			Handler:    _OpOnlineServiceCommon_SyncClientDeployInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sudo/service/online_service_common.proto",
}
