// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: protobuf/mpc_virtual_service/platform/yellowpage.proto

package common

import (
	enums "github.com/sudo-privacy/sudo-sdk-go/protobuf/basic/protobuf/enums"
	paginator "github.com/sudo-privacy/sudo-sdk-go/protobuf/basic/protobuf/virtualservice/platformpb/paginator"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type YellowPage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedTs   int64                        `protobuf:"varint,2,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	UpdatedTs   int64                        `protobuf:"varint,3,opt,name=updated_ts,json=updatedTs,proto3" json:"updated_ts,omitempty"`
	ClientParty string                       `protobuf:"bytes,4,opt,name=client_party,json=clientParty,proto3" json:"client_party,omitempty"`
	ServerParty string                       `protobuf:"bytes,5,opt,name=server_party,json=serverParty,proto3" json:"server_party,omitempty"`
	ServiceType enums.YellowPage_ServiceType `protobuf:"varint,6,opt,name=service_type,json=serviceType,proto3,enum=sudo.protobuf.enums.YellowPage_ServiceType" json:"service_type,omitempty"`
	Url         string                       `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	// Deprecated: Do not use.
	WithoutSsl bool `protobuf:"varint,8,opt,name=without_ssl,json=withoutSsl,proto3" json:"without_ssl,omitempty"`
	// Deprecated: Do not use.
	Ip string `protobuf:"bytes,9,opt,name=ip,proto3" json:"ip,omitempty"`
	// Deprecated: Do not use.
	Port string `protobuf:"bytes,10,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *YellowPage) Reset() {
	*x = YellowPage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YellowPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YellowPage) ProtoMessage() {}

func (x *YellowPage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YellowPage.ProtoReflect.Descriptor instead.
func (*YellowPage) Descriptor() ([]byte, []int) {
	return file_protobuf_mpc_virtual_service_platform_yellowpage_proto_rawDescGZIP(), []int{0}
}

func (x *YellowPage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *YellowPage) GetCreatedTs() int64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

func (x *YellowPage) GetUpdatedTs() int64 {
	if x != nil {
		return x.UpdatedTs
	}
	return 0
}

func (x *YellowPage) GetClientParty() string {
	if x != nil {
		return x.ClientParty
	}
	return ""
}

func (x *YellowPage) GetServerParty() string {
	if x != nil {
		return x.ServerParty
	}
	return ""
}

func (x *YellowPage) GetServiceType() enums.YellowPage_ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return enums.YellowPage_UNKNOWN_SERVICE
}

func (x *YellowPage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Deprecated: Do not use.
func (x *YellowPage) GetWithoutSsl() bool {
	if x != nil {
		return x.WithoutSsl
	}
	return false
}

// Deprecated: Do not use.
func (x *YellowPage) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// Deprecated: Do not use.
func (x *YellowPage) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type CreateOrUpdateYellowPageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	YellowPage *YellowPage `protobuf:"bytes,1,opt,name=yellow_page,json=yellowPage,proto3" json:"yellow_page,omitempty"`
}

func (x *CreateOrUpdateYellowPageRequest) Reset() {
	*x = CreateOrUpdateYellowPageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateYellowPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateYellowPageRequest) ProtoMessage() {}

func (x *CreateOrUpdateYellowPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateYellowPageRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateYellowPageRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_mpc_virtual_service_platform_yellowpage_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrUpdateYellowPageRequest) GetYellowPage() *YellowPage {
	if x != nil {
		return x.YellowPage
	}
	return nil
}

type CreateOrUpdateYellowPageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	YellowPage *YellowPage `protobuf:"bytes,1,opt,name=yellow_page,json=yellowPage,proto3" json:"yellow_page,omitempty"`
}

func (x *CreateOrUpdateYellowPageResponse) Reset() {
	*x = CreateOrUpdateYellowPageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateYellowPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateYellowPageResponse) ProtoMessage() {}

func (x *CreateOrUpdateYellowPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateYellowPageResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateYellowPageResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_mpc_virtual_service_platform_yellowpage_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrUpdateYellowPageResponse) GetYellowPage() *YellowPage {
	if x != nil {
		return x.YellowPage
	}
	return nil
}

type ListYellowPagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientParty string                       `protobuf:"bytes,1,opt,name=client_party,json=clientParty,proto3" json:"client_party,omitempty"`
	ServerParty string                       `protobuf:"bytes,2,opt,name=server_party,json=serverParty,proto3" json:"server_party,omitempty"`
	ServiceType enums.YellowPage_ServiceType `protobuf:"varint,3,opt,name=service_type,json=serviceType,proto3,enum=sudo.protobuf.enums.YellowPage_ServiceType" json:"service_type,omitempty"`
	Paginator   *paginator.Paginator         `protobuf:"bytes,4,opt,name=paginator,proto3" json:"paginator,omitempty"`
}

func (x *ListYellowPagesRequest) Reset() {
	*x = ListYellowPagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListYellowPagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListYellowPagesRequest) ProtoMessage() {}

func (x *ListYellowPagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListYellowPagesRequest.ProtoReflect.Descriptor instead.
func (*ListYellowPagesRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_mpc_virtual_service_platform_yellowpage_proto_rawDescGZIP(), []int{3}
}

func (x *ListYellowPagesRequest) GetClientParty() string {
	if x != nil {
		return x.ClientParty
	}
	return ""
}

func (x *ListYellowPagesRequest) GetServerParty() string {
	if x != nil {
		return x.ServerParty
	}
	return ""
}

func (x *ListYellowPagesRequest) GetServiceType() enums.YellowPage_ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return enums.YellowPage_UNKNOWN_SERVICE
}

func (x *ListYellowPagesRequest) GetPaginator() *paginator.Paginator {
	if x != nil {
		return x.Paginator
	}
	return nil
}

type ListYellowPagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []*YellowPage `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total int64         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListYellowPagesResponse) Reset() {
	*x = ListYellowPagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListYellowPagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListYellowPagesResponse) ProtoMessage() {}

func (x *ListYellowPagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListYellowPagesResponse.ProtoReflect.Descriptor instead.
func (*ListYellowPagesResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_mpc_virtual_service_platform_yellowpage_proto_rawDescGZIP(), []int{4}
}

func (x *ListYellowPagesResponse) GetData() []*YellowPage {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListYellowPagesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteYellowPageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteYellowPageRequest) Reset() {
	*x = DeleteYellowPageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteYellowPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteYellowPageRequest) ProtoMessage() {}

func (x *DeleteYellowPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteYellowPageRequest.ProtoReflect.Descriptor instead.
func (*DeleteYellowPageRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_mpc_virtual_service_platform_yellowpage_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteYellowPageRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_protobuf_mpc_virtual_service_platform_yellowpage_proto protoreflect.FileDescriptor

var file_protobuf_mpc_virtual_service_platform_yellowpage_proto_rawDesc = []byte{
	0x0a, 0x36, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6d, 0x70, 0x63, 0x5f, 0x76,
	0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x79, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x70, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x79, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x70, 0x61, 0x67, 0x65, 0x1a, 0x3a, 0x73, 0x75, 0x64, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6d, 0x70, 0x63, 0x5f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61,
	0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1f, 0x73, 0x75, 0x64, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xd3, 0x02, 0x0a, 0x0a, 0x59, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x50, 0x61,
	0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x54, 0x73,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x61,
	0x72, 0x74, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x61,
	0x72, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x50, 0x61, 0x72, 0x74, 0x79, 0x12, 0x4e, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x73,
	0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x65, 0x6e, 0x75,
	0x6d, 0x73, 0x2e, 0x59, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x50, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x23, 0x0a, 0x0b, 0x77, 0x69, 0x74, 0x68,
	0x6f, 0x75, 0x74, 0x5f, 0x73, 0x73, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x42, 0x02, 0x18,
	0x01, 0x52, 0x0a, 0x77, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x53, 0x73, 0x6c, 0x12, 0x12, 0x0a,
	0x02, 0x69, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x42, 0x02, 0x18, 0x01, 0x52, 0x02, 0x69,
	0x70, 0x12, 0x16, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x02, 0x18, 0x01, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x6c, 0x0a, 0x1f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x59, 0x65, 0x6c, 0x6c, 0x6f,
	0x77, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x49, 0x0a, 0x0b,
	0x79, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x79, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x70, 0x61, 0x67, 0x65,
	0x2e, 0x59, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x50, 0x61, 0x67, 0x65, 0x52, 0x0a, 0x79, 0x65, 0x6c,
	0x6c, 0x6f, 0x77, 0x50, 0x61, 0x67, 0x65, 0x22, 0x6d, 0x0a, 0x20, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x59, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x50,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0b, 0x79,
	0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x79, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x70, 0x61, 0x67, 0x65, 0x2e,
	0x59, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x50, 0x61, 0x67, 0x65, 0x52, 0x0a, 0x79, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x50, 0x61, 0x67, 0x65, 0x22, 0xf9, 0x01, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x59,
	0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x50, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x61, 0x72, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50,
	0x61, 0x72, 0x74, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x70,
	0x61, 0x72, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x50, 0x61, 0x72, 0x74, 0x79, 0x12, 0x4e, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e,
	0x73, 0x75, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x65, 0x6e,
	0x75, 0x6d, 0x73, 0x2e, 0x59, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x50, 0x61, 0x67, 0x65, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x49, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x73, 0x75, 0x64,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x09, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x6f, 0x72, 0x22, 0x6d, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x59, 0x65, 0x6c, 0x6c, 0x6f, 0x77,
	0x50, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e,
	0x79, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x59, 0x65, 0x6c, 0x6c, 0x6f,
	0x77, 0x50, 0x61, 0x67, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x22, 0x29, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x59, 0x65, 0x6c, 0x6c, 0x6f,
	0x77, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x42, 0x37, 0x5a, 0x35,
	0x70, 0x61, 0x61, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x70, 0x62, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_mpc_virtual_service_platform_yellowpage_proto_rawDescOnce sync.Once
	file_protobuf_mpc_virtual_service_platform_yellowpage_proto_rawDescData = file_protobuf_mpc_virtual_service_platform_yellowpage_proto_rawDesc
)

func file_protobuf_mpc_virtual_service_platform_yellowpage_proto_rawDescGZIP() []byte {
	file_protobuf_mpc_virtual_service_platform_yellowpage_proto_rawDescOnce.Do(func() {
		file_protobuf_mpc_virtual_service_platform_yellowpage_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_mpc_virtual_service_platform_yellowpage_proto_rawDescData)
	})
	return file_protobuf_mpc_virtual_service_platform_yellowpage_proto_rawDescData
}

var file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protobuf_mpc_virtual_service_platform_yellowpage_proto_goTypes = []interface{}{
	(*YellowPage)(nil),                       // 0: protobuf.platform.yellowpage.YellowPage
	(*CreateOrUpdateYellowPageRequest)(nil),  // 1: protobuf.platform.yellowpage.CreateOrUpdateYellowPageRequest
	(*CreateOrUpdateYellowPageResponse)(nil), // 2: protobuf.platform.yellowpage.CreateOrUpdateYellowPageResponse
	(*ListYellowPagesRequest)(nil),           // 3: protobuf.platform.yellowpage.ListYellowPagesRequest
	(*ListYellowPagesResponse)(nil),          // 4: protobuf.platform.yellowpage.ListYellowPagesResponse
	(*DeleteYellowPageRequest)(nil),          // 5: protobuf.platform.yellowpage.DeleteYellowPageRequest
	(enums.YellowPage_ServiceType)(0),        // 6: sudo.protobuf.enums.YellowPage.ServiceType
	(*paginator.Paginator)(nil),              // 7: sudo.protobuf.platform.paginator.Paginator
}
var file_protobuf_mpc_virtual_service_platform_yellowpage_proto_depIdxs = []int32{
	6, // 0: protobuf.platform.yellowpage.YellowPage.service_type:type_name -> sudo.protobuf.enums.YellowPage.ServiceType
	0, // 1: protobuf.platform.yellowpage.CreateOrUpdateYellowPageRequest.yellow_page:type_name -> protobuf.platform.yellowpage.YellowPage
	0, // 2: protobuf.platform.yellowpage.CreateOrUpdateYellowPageResponse.yellow_page:type_name -> protobuf.platform.yellowpage.YellowPage
	6, // 3: protobuf.platform.yellowpage.ListYellowPagesRequest.service_type:type_name -> sudo.protobuf.enums.YellowPage.ServiceType
	7, // 4: protobuf.platform.yellowpage.ListYellowPagesRequest.paginator:type_name -> sudo.protobuf.platform.paginator.Paginator
	0, // 5: protobuf.platform.yellowpage.ListYellowPagesResponse.data:type_name -> protobuf.platform.yellowpage.YellowPage
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_protobuf_mpc_virtual_service_platform_yellowpage_proto_init() }
func file_protobuf_mpc_virtual_service_platform_yellowpage_proto_init() {
	if File_protobuf_mpc_virtual_service_platform_yellowpage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YellowPage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateYellowPageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateYellowPageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListYellowPagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListYellowPagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteYellowPageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_mpc_virtual_service_platform_yellowpage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_mpc_virtual_service_platform_yellowpage_proto_goTypes,
		DependencyIndexes: file_protobuf_mpc_virtual_service_platform_yellowpage_proto_depIdxs,
		MessageInfos:      file_protobuf_mpc_virtual_service_platform_yellowpage_proto_msgTypes,
	}.Build()
	File_protobuf_mpc_virtual_service_platform_yellowpage_proto = out.File
	file_protobuf_mpc_virtual_service_platform_yellowpage_proto_rawDesc = nil
	file_protobuf_mpc_virtual_service_platform_yellowpage_proto_goTypes = nil
	file_protobuf_mpc_virtual_service_platform_yellowpage_proto_depIdxs = nil
}
