// Copyright 2022 Sudo Technology Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: sudo/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Endpoint_Scheme int32

const (
	Endpoint_HTTP  Endpoint_Scheme = 0
	Endpoint_HTTPS Endpoint_Scheme = 1
	Endpoint_WS    Endpoint_Scheme = 2
)

// Enum value maps for Endpoint_Scheme.
var (
	Endpoint_Scheme_name = map[int32]string{
		0: "HTTP",
		1: "HTTPS",
		2: "WS",
	}
	Endpoint_Scheme_value = map[string]int32{
		"HTTP":  0,
		"HTTPS": 1,
		"WS":    2,
	}
)

func (x Endpoint_Scheme) Enum() *Endpoint_Scheme {
	p := new(Endpoint_Scheme)
	*p = x
	return p
}

func (x Endpoint_Scheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Endpoint_Scheme) Descriptor() protoreflect.EnumDescriptor {
	return file_sudo_common_proto_enumTypes[0].Descriptor()
}

func (Endpoint_Scheme) Type() protoreflect.EnumType {
	return &file_sudo_common_proto_enumTypes[0]
}

func (x Endpoint_Scheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Endpoint_Scheme.Descriptor instead.
func (Endpoint_Scheme) EnumDescriptor() ([]byte, []int) {
	return file_sudo_common_proto_rawDescGZIP(), []int{0, 0}
}

type Endpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host   string          `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Scheme Endpoint_Scheme `protobuf:"varint,2,opt,name=scheme,proto3,enum=common.Endpoint_Scheme" json:"scheme,omitempty"`
	Port   int64           `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_sudo_common_proto_rawDescGZIP(), []int{0}
}

func (x *Endpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Endpoint) GetScheme() Endpoint_Scheme {
	if x != nil {
		return x.Scheme
	}
	return Endpoint_HTTP
}

func (x *Endpoint) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ResourceRequirement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *ResourceRequirement_Spec `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Limit   *ResourceRequirement_Spec `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ResourceRequirement) Reset() {
	*x = ResourceRequirement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequirement) ProtoMessage() {}

func (x *ResourceRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequirement.ProtoReflect.Descriptor instead.
func (*ResourceRequirement) Descriptor() ([]byte, []int) {
	return file_sudo_common_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceRequirement) GetRequest() *ResourceRequirement_Spec {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ResourceRequirement) GetLimit() *ResourceRequirement_Spec {
	if x != nil {
		return x.Limit
	}
	return nil
}

type ResourceRequirement_Spec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu    string `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory string `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
}

func (x *ResourceRequirement_Spec) Reset() {
	*x = ResourceRequirement_Spec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sudo_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceRequirement_Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequirement_Spec) ProtoMessage() {}

func (x *ResourceRequirement_Spec) ProtoReflect() protoreflect.Message {
	mi := &file_sudo_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequirement_Spec.ProtoReflect.Descriptor instead.
func (*ResourceRequirement_Spec) Descriptor() ([]byte, []int) {
	return file_sudo_common_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ResourceRequirement_Spec) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ResourceRequirement_Spec) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

var File_sudo_common_proto protoreflect.FileDescriptor

var file_sudo_common_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x75, 0x64, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x8a, 0x01, 0x0a, 0x08,
	0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x06,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x22, 0x25, 0x0a, 0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x48,
	0x54, 0x54, 0x50, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x54, 0x54, 0x50, 0x53, 0x10, 0x01,
	0x12, 0x06, 0x0a, 0x02, 0x57, 0x53, 0x10, 0x02, 0x22, 0xbb, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x3a, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53,
	0x70, 0x65, 0x63, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x1a, 0x30, 0x0a, 0x04, 0x53, 0x70, 0x65, 0x63, 0x12, 0x10, 0x0a, 0x03,
	0x63, 0x70, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sudo_common_proto_rawDescOnce sync.Once
	file_sudo_common_proto_rawDescData = file_sudo_common_proto_rawDesc
)

func file_sudo_common_proto_rawDescGZIP() []byte {
	file_sudo_common_proto_rawDescOnce.Do(func() {
		file_sudo_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_sudo_common_proto_rawDescData)
	})
	return file_sudo_common_proto_rawDescData
}

var file_sudo_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sudo_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sudo_common_proto_goTypes = []interface{}{
	(Endpoint_Scheme)(0),             // 0: common.Endpoint.Scheme
	(*Endpoint)(nil),                 // 1: common.Endpoint
	(*ResourceRequirement)(nil),      // 2: common.ResourceRequirement
	(*ResourceRequirement_Spec)(nil), // 3: common.ResourceRequirement.Spec
}
var file_sudo_common_proto_depIdxs = []int32{
	0, // 0: common.Endpoint.scheme:type_name -> common.Endpoint.Scheme
	3, // 1: common.ResourceRequirement.request:type_name -> common.ResourceRequirement.Spec
	3, // 2: common.ResourceRequirement.limit:type_name -> common.ResourceRequirement.Spec
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sudo_common_proto_init() }
func file_sudo_common_proto_init() {
	if File_sudo_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sudo_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Endpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceRequirement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sudo_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceRequirement_Spec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sudo_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sudo_common_proto_goTypes,
		DependencyIndexes: file_sudo_common_proto_depIdxs,
		EnumInfos:         file_sudo_common_proto_enumTypes,
		MessageInfos:      file_sudo_common_proto_msgTypes,
	}.Build()
	File_sudo_common_proto = out.File
	file_sudo_common_proto_rawDesc = nil
	file_sudo_common_proto_goTypes = nil
	file_sudo_common_proto_depIdxs = nil
}
